spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 1dad3f395993fb1d4d15
            client-secret: 0b49084f86173df4931fa92c9a7b944a88cbeb27
          google:
            client-id: 350946050687-cfdu3kqfdn23vltdts9oatkgd0vs5lf7.apps.googleusercontent.com
            client-secret: CkJxGFc8OkRdwIjwxARTLGZh
          spotify:
            client-id: 3a3e56b01c5f4777a9f91f2542fa5c40
            client-secret: 37630cab9a1b4af7a5fbe2c04c507940
            provider: spotify-provider
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/callback
            scope: user-read-private,user-read-email
        provider:
          spotify-provider:
            authorization-uri: https://accounts.spotify.com/authorize?show_dialog=true
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id

#logging:
#  level:
#    org.springframework.security: DEBUG
